# Generated by Django 3.2.5 on 2021-08-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20210817_2234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="о себе"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="дата рождения"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="facebook_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="facebook"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="instagram"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="users/%Y/%m/%d", verbose_name="фотография"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="twitter"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="website"
            ),
        ),
    ]
