# Generated by Django 3.2.5 on 2021-09-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20210818_1637"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="имя пользователя"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="адрес электронной почты"
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="тема")),
                (
                    "message",
                    models.TextField(max_length=2000, verbose_name="сообщение"),
                ),
            ],
        ),
    ]
