# Generated by Django 3.2.5 on 2021-10-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default=1, verbose_name="о себе"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="facebook_url",
            field=models.CharField(
                blank=True, default=1, max_length=255, verbose_name="facebook"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram_url",
            field=models.CharField(
                blank=True, default=1, max_length=255, verbose_name="instagram"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_url",
            field=models.CharField(
                blank=True, default=1, max_length=255, verbose_name="twitter"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="website_url",
            field=models.CharField(
                blank=True, default=1, max_length=255, verbose_name="website"
            ),
            preserve_default=False,
        ),
    ]
