# Generated by Django 3.2.4 on 2021-07-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("user_email", models.EmailField(max_length=254)),
                ("comment_text", models.TextField()),
                ("comment_created_date", models.DateTimeField(auto_now_add=True)),
                ("comment_updated_date", models.DateTimeField(auto_now=True)),
                ("comment_active", models.BooleanField(default=True)),
                (
                    "related_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "ordering": ("comment_created_date",),
            },
        ),
    ]
