# Generated by Django 3.2.5 on 2021-08-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_status",
            field=models.CharField(
                choices=[("черновик", "Черновик"), ("опубликовано", "Опубликовано")],
                default="опубликовано",
                max_length=12,
            ),
        ),
    ]
