# Generated by Django 3.2.5 on 2021-08-15 15:32

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0005_alter_post_post_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_likes",
            field=models.ManyToManyField(
                related_name="blog", to=settings.AUTH_USER_MODEL, verbose_name="лайки"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_text",
            field=models.TextField(verbose_name="комментарий"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="дата изменения"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_email",
            field=models.EmailField(max_length=254, verbose_name="е-mail пользователя"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_name",
            field=models.CharField(max_length=50, verbose_name="имя пользователя"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_published_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_status",
            field=models.CharField(
                choices=[("черновик", "Черновик"), ("опубликовано", "Опубликовано")],
                default="опубликовано",
                max_length=12,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_text",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="текст публикации"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_title",
            field=models.CharField(max_length=250, verbose_name="заголовок публикации"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_unique_mark",
            field=models.SlugField(
                max_length=250,
                unique_for_date="post_published_date",
                verbose_name="уникальная метка",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="дата изменения"),
        ),
    ]
