# Generated by Django 3.2.5 on 2021-08-16 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0007_remove_comment_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user_name",
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.user",
                verbose_name="автор комментария",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="post_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор публикации",
            ),
        ),
    ]
