# Generated by Django 3.2.5 on 2021-08-17 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_auto_20210816_2242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="related_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.post",
                verbose_name="связанная публикация",
            ),
        ),
    ]
