# Generated by Django 3.2.5 on 2021-09-02 07:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_comment_related_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created_date",)},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-published_date",)},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_author",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_created_date",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_active",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_text",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_updated_date",
            new_name="updated_date",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_author",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_created_date",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_likes",
            new_name="likes",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_published_date",
            new_name="published_date",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_tags",
            new_name="tags",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_title",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_unique_mark",
            new_name="unique_mark",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_updated_date",
            new_name="updated_date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_text",
        ),
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.CharField(max_length=255, null=True, verbose_name="website"),
        ),
        migrations.AddField(
            model_name="post",
            name="text",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="текст публикации"
            ),
        ),
    ]
