# Generated by Django 3.2.5 on 2021-09-02 08:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_auto_20210902_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.CharField(max_length=250, verbose_name="фото публикации"),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor.fields.RichTextField(verbose_name="текст публикации"),
        ),
    ]
