# Generated by Django 3.2.5 on 2021-09-02 19:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_auto_20210902_1102"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_date",)},
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=ckeditor.fields.RichTextField(verbose_name="комментарий"),
        ),
        migrations.AlterField(
            model_name="post",
            name="unique_mark",
            field=models.SlugField(
                max_length=250,
                unique_for_date="published_date",
                verbose_name="уникальная метка",
            ),
        ),
    ]
