# Generated by Django 3.2.5 on 2021-09-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WTManufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(max_length=250, verbose_name="производитель"),
                ),
                ("country", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="WindTurbine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nominal_power", models.FloatField(max_length=250)),
                ("power_curve", models.JSONField()),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculators.wtmanufacturer",
                    ),
                ),
            ],
        ),
    ]
