# Generated by Django 3.2.5 on 2021-09-09 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculators", "0002_auto_20210905_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smmanufacturer",
            name="country",
            field=models.CharField(max_length=250, verbose_name="страна"),
        ),
        migrations.AlterField(
            model_name="solarmodule",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="calculators.smmanufacturer",
                verbose_name="производитель",
            ),
        ),
        migrations.AlterField(
            model_name="solarmodule",
            name="model_name",
            field=models.CharField(max_length=250, verbose_name="название модели"),
        ),
        migrations.AlterField(
            model_name="solarmodule",
            name="nominal_power",
            field=models.FloatField(
                max_length=250, verbose_name="номинальная мощность, кВт"
            ),
        ),
        migrations.AlterField(
            model_name="solarmodule",
            name="sm_size",
            field=models.FloatField(max_length=250, verbose_name="площадь в м2"),
        ),
        migrations.AlterField(
            model_name="windturbine",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="calculators.wtmanufacturer",
                verbose_name="производитель",
            ),
        ),
        migrations.AlterField(
            model_name="windturbine",
            name="model_name",
            field=models.CharField(max_length=250, verbose_name="название модели"),
        ),
        migrations.AlterField(
            model_name="windturbine",
            name="nominal_power",
            field=models.FloatField(
                max_length=250, verbose_name="номинальная мощность, кВт"
            ),
        ),
        migrations.AlterField(
            model_name="windturbine",
            name="power_curve",
            field=models.JSONField(verbose_name="кривая мощности"),
        ),
        migrations.AlterField(
            model_name="wtmanufacturer",
            name="company",
            field=models.CharField(max_length=250, verbose_name="компания"),
        ),
        migrations.AlterField(
            model_name="wtmanufacturer",
            name="country",
            field=models.CharField(max_length=250, verbose_name="страна"),
        ),
        migrations.CreateModel(
            name="WindTurbineCatalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.FloatField(max_length=250, verbose_name="стоимость, $"),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wt_manufacturer",
                        to="calculators.wtmanufacturer",
                        verbose_name="производитель",
                    ),
                ),
                (
                    "model_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wt_model_name",
                        to="calculators.windturbine",
                        verbose_name="название модели",
                    ),
                ),
                (
                    "nominal_power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculators.windturbine",
                        verbose_name="номинальная мощность, кВт",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarModuleCatalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.FloatField(max_length=250, verbose_name="стоимость, $"),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sm_manufacturer",
                        to="calculators.smmanufacturer",
                        verbose_name="производитель",
                    ),
                ),
                (
                    "model_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sm_model_name",
                        to="calculators.solarmodule",
                        verbose_name="название модели",
                    ),
                ),
                (
                    "nominal_power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculators.solarmodule",
                        verbose_name="номинальная мощность, кВт",
                    ),
                ),
            ],
        ),
    ]
