# Generated by Django 3.2.5 on 2021-09-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculators", "0003_auto_20210909_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="windturbinecatalogue",
            name="country_name",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="calculators.wtmanufacturer",
                verbose_name="производитель",
            ),
            preserve_default=False,
        ),
    ]
