# Generated by Django 3.2.5 on 2021-09-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculators", "0004_windturbinecatalogue_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="windturbinecatalogue",
            name="country_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturer",
                to="calculators.wtmanufacturer",
                verbose_name="производитель",
            ),
        ),
        migrations.AlterField(
            model_name="windturbinecatalogue",
            name="model_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wt_model_name",
                to="calculators.windturbine",
                verbose_name="название модели",
            ),
        ),
        migrations.AlterField(
            model_name="windturbinecatalogue",
            name="nominal_power",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wt_nominal_power",
                to="calculators.windturbine",
                verbose_name="номинальная мощность, кВт",
            ),
        ),
    ]
