# Generated by Django 3.2.5 on 2021-09-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculators", "0005_auto_20210911_1717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="windturbinecatalogue",
            name="country_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wtc_country_name",
                to="calculators.wtmanufacturer",
                verbose_name="производитель",
            ),
        ),
        migrations.AlterField(
            model_name="windturbinecatalogue",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wtc_manufacturer",
                to="calculators.wtmanufacturer",
                verbose_name="производитель",
            ),
        ),
        migrations.AlterField(
            model_name="windturbinecatalogue",
            name="model_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wtc_model_name",
                to="calculators.windturbine",
                verbose_name="название модели",
            ),
        ),
        migrations.AlterField(
            model_name="windturbinecatalogue",
            name="nominal_power",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wtc_nominal_power",
                to="calculators.windturbine",
                verbose_name="номинальная мощность, кВт",
            ),
        ),
    ]
