# Generated by Django 3.2.5 on 2021-09-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculators", "0006_auto_20210911_2239"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WindTurbineCatalogue",
        ),
    ]
