# Generated by Django 3.2.5 on 2021-09-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculators", "0007_delete_windturbinecatalogue"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SolarModuleCatalogue",
        ),
    ]
