# Generated by Django 3.2.5 on 2021-09-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculators", "0008_delete_solarmodulecatalogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="windturbine",
            name="hub_height",
            field=models.JSONField(default=(50, 100), verbose_name="высота башни, м"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="solarmodule",
            name="sm_size",
            field=models.FloatField(max_length=250, verbose_name="площадь, м2"),
        ),
    ]
