# Generated by Django 3.2.5 on 2021-09-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculators", "0010_remove_windturbine_hub_height"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roughness_name",
                    models.CharField(max_length=250, verbose_name="тип ландшафта"),
                ),
                (
                    "roughness",
                    models.FloatField(
                        max_length=250,
                        verbose_name="значение шероховатости подстилающей поверхности",
                    ),
                ),
            ],
        ),
    ]
