# Generated by Django 3.2.5 on 2021-09-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculators", "0011_windparameters"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WindParameters",
            new_name="WindParameter",
        ),
    ]
