# Generated by Django 3.2.5 on 2021-09-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculators", "0012_rename_windparameters_windparameter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smmanufacturer",
            options={
                "verbose_name": "производитель СМ",
                "verbose_name_plural": "производители СМ",
            },
        ),
        migrations.AlterModelOptions(
            name="solarmodule",
            options={
                "verbose_name": "солнечный модуль",
                "verbose_name_plural": "солнечные модули",
            },
        ),
        migrations.AlterModelOptions(
            name="windparameter",
            options={
                "verbose_name": "параметр ветра",
                "verbose_name_plural": "параметры ветра",
            },
        ),
        migrations.AlterModelOptions(
            name="windturbine",
            options={
                "verbose_name": "ветрогенератор",
                "verbose_name_plural": "ветрогенераторы",
            },
        ),
        migrations.AlterModelOptions(
            name="wtmanufacturer",
            options={
                "verbose_name": "производитель ВЭУ",
                "verbose_name_plural": "производители ВЭУ",
            },
        ),
    ]
